apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: app-of-apps
spec:
  project: default
  destination:
    server:  https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: git@github.com:meshachdamilare/local_cluster_playground.git
    targetRevision: main
    path: application-sets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - ServerSideApply=true