apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  labels:
    app: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-app
          image: speedyrogue007/frontend_app:latest
          command: ["apachectl" , "-D" , "FOREGROUND"]
          ports:
            - containerPort: 80
        - name: apache-exporter
          image: bitnami/apache-exporter
          ports:
            -  containerPort: 9117

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-app
spec:
  selector:
    app: frontend-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: metrics
      protocol: TCP
      port: 9117
      targetPort: 9117
  type: ClusterIP