apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  namespace: argocd
  name: apache
spec:
  generators:
  - list:
      elements:
      - cluster: minikube
        url: https://kubernetes.default.svc
        branch: main
      # - cluster: dev
      #   url: https://kubernetes.default.svc
      #   branch: main
  template:
    metadata:
      name: '{{cluster}}-apache'
    spec:
      project: default
      source:
        repoURL: git@github.com:meshachdamilare/local_cluster_argocd-apps.git
        targetRevision: '{{branch}}'
        path: applications/apache/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: webservices
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - Validate=true
        - CreateNamespace=true
        - ServerSideApply=true