apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  namespace: argocd
  name: frontend
spec:
  generators:
  - list:
      elements:
      - cluster: minikube
        url: https://kubernetes.default.svc
        branch: main
      # - cluster: dev
      #   url: https://kubernetes.default.svc
      #   branch: main
  template:
    metadata:
      name: '{{cluster}}-frontend'
    spec:
      project: default
      source:
        repoURL: git@github.com:meshachdamilare/local-minikube-argocd-apps.git
        targetRevision: '{{branch}}'
        path: frontend/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: webservices
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - Validate=true
        - CreateNamespace=true
        - ServerSideApply=true