apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: webservices

helmCharts:
  - name: apache
    repo:  https://charts.bitnami.com/bitnami
    version: 11.3.2
    releaseName: my-apache